
[platformio]
; uncomment this line to build on Macbook local dir instead of NFS mount
workspace_dir = /var/tmp
default_envs = ec2

[common]
;platform = espressif32@6.3.2
;platform = espressif32
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32doit-devkit-v1
framework = arduino
upload_speed = 460800
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
;build_type = debug
build_type = release
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_flags =
;	-D HOSTNAME=esp32
	-D ELEGANTOTA
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D WEBSERIAL
	-D APPHANDLER
;	-D DEBUG	; when things go sideways
	-D WIFI
	-D NTP
	-D WEB
	-D REACT
	-D WATER
	-D ECHO
	-Os	; optimize for size
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-D CORE_DEBUG_LEVEL=0
  -DCONFIG_ESP32_PANIC_PRINT_REBOOT
  -DCONFIG_ESP32_PANIC_PRINT_STACK_TRACE
  -DCONFIG_ESP32_PANIC_GDBSTUB_ENABLED
;  -Wl,--wrap=esp_panic_handler
;  -DCORE_DEBUG_LEVEL=1
;  -DCONFIG_ASYNC_TCP_RUNNING_CORE=1
;  -DCONFIG_ASYNC_TCP_STACK_SIZE=8192
;  -DCONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH=4096
;	-I tools/sdk/esp32s2/include/mdns/include
lib_compat_mode = strict
lib_ldf_mode = deep
lib_deps = 
	https://github.com/ESP32Async/AsyncTCP
	https://github.com/ESP32Async/ESPAsyncWebServer
	https://github.com/ayushsharma82/ElegantOTA
	bblanchon/ArduinoJson@^7.2.0
	mairas/ReactESP@^2.0.0
	https://github.com/adafruit/Adafruit_INA219.git
	https://github.com/wjquigs11/movingAvg

[env:macbook]
extends = common
board = esp32dev
build_flags =
    ${common.build_flags}
	-D LED_BUILTIN=2
lib_deps =
	${common.lib_deps}
	/Users/wjquigs/Dropbox/ESP/WebSerialPro-Essential-Bundle-v2-1-0.zip

[env:graviton]
extends = common
board = esp32dev
build_flags =
    ${common.build_flags}
	-D LED_BUILTIN=2
lib_deps =
	${common.lib_deps}
	/home/wjquigs/nfs/ESP/WebSerialPro-Essential-Bundle-v2-1-0.zip

[env:ec2]
extends = common
board = esp32dev
build_flags =
    ${common.build_flags}
	-D LED_BUILTIN=2
lib_deps =
	${common.lib_deps}
	/home/ec2-user/ESP/WebSerialPro-Essential-Bundle-v2-1-0.zip

[env:feather]
extends = common
;board_build.partitions = 4Mpart.csv
board = adafruit_feather_esp32s2_reversetft
build_type = release
monitor_filters = esp32_exception_decoder
upload_resetmethod = no_reset
lib_deps = 
	${common.lib_deps}
;	adafruit/Adafruit ST7735 and ST7789 Library@^1.10.4
;	adafruit/Adafruit GFX Library@^1.11.9
;	adafruit/Adafruit BusIO@^1.16.1
;	adafruit/Adafruit seesaw Library@^1.7.8
;	adafruit/Adafruit MAX1704X@^1.0.3
;	adafruit/Adafruit NeoPixel@^1.12.2
;	adafruit/Adafruit BME280 Library@^2.2.4
build_flags =
    ${common.build_flags}
	-DFEATHER=1
	-DCORE_DEBUG_LEVEL=1
	-Os

[env:rsync]
platform = native
extra_scripts = sync.py
