; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
;board = esp32-c3-devkitm-1
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
upload_speed = 460800
;upload_port = /dev/cu.usbserial-A5069RR4
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_type = release
build_flags =
	-D ELEGANTOTA
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D WEBSERIAL
;	-D APPHANDLER
	-D WIFI
;	-D NTP
;	-D DEEPSLEEP
;	-D TEMPLATE
lib_compat_mode = strict
lib_ldf_mode = deep
lib_deps = 
	https://github.com/ESP32Async/AsyncTCP#v3.4.9
	https://github.com/ESP32Async/ESPAsyncWebServer#v3.8.1
	https://github.com/ayushsharma82/ElegantOTA
	bblanchon/ArduinoJson@^7.2.0
;	https://github.com/ayushsharma82/WebSerial
;	on Macbook
;	/Users/wjquigs/Dropbox/ESP/WebSerialPro-Essential-Bundle-v2-1-0.zip
;	on remote build server
	/home/wjquigs/nfs/ESP/WebSerialPro-Essential-Bundle-v2-1-0.zip

[env:ota]
extends = env:esp32doit-devkit-v1
upload_protocol = espota
upload_port = 192.168.68.53
upload_flags = 
	--port=3232